services:
  backend:
    build: backend
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/swstarter
    depends_on:
      - mongodb
    networks:
      - docker-network
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - docker-network
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: --quiet
    networks:
      - docker-network
volumes:
  mongodb_data:
networks:
  docker-network: